package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "path_sum_iii",
    srcs = ["path_sum_iii.cc"],
    # malloc = "@com_google_tcmalloc//tcmalloc",
    deps = [
        "@com_github_google_glog//:glog",
        "@com_github_gflags_gflags//:gflags",
    ],
    # linkopts = [ '-lunwind', '-lm', '-lpthread', '-lrt', '-ltcmalloc_and_profiler'],
    linkopts = ['-lm', '-lpthread'],
)

cc_binary(
    name = "lowest_common_ancestor_of_a_binary_tree",
    srcs = ["lowest_common_ancestor_of_a_binary_tree.cc"],
    # malloc = "@com_google_tcmalloc//tcmalloc",
    deps = [
        "@com_github_google_glog//:glog",
        "@com_github_gflags_gflags//:gflags",
    ],
    # linkopts = [ '-lunwind', '-lm', '-lpthread', '-lrt', '-ltcmalloc_and_profiler'],
    linkopts = ['-lm', '-lpthread'],
)

cc_binary(
    name = "binary_tree_maximum_path_sum",
    srcs = ["binary_tree_maximum_path_sum.cc"],
    # malloc = "@com_google_tcmalloc//tcmalloc",
    deps = [
        "@com_github_google_glog//:glog",
        "@com_github_gflags_gflags//:gflags",
    ],
    # linkopts = [ '-lunwind', '-lm', '-lpthread', '-lrt', '-ltcmalloc_and_profiler'],
    linkopts = ['-lm', '-lpthread'],
)

cc_binary(
    name = "er_cha_shu_de_shen_du_lcof",
    srcs = ["er_cha_shu_de_shen_du_lcof.cc"],
    # malloc = "@com_google_tcmalloc//tcmalloc",
    deps = [
        "@com_github_google_glog//:glog",
        "@com_github_gflags_gflags//:gflags",
    ],
    # linkopts = [ '-lunwind', '-lm', '-lpthread', '-lrt', '-ltcmalloc_and_profiler'],
    linkopts = ['-lm', '-lpthread'],
)
cc_binary(
    name = "coloring_a_border",
    srcs = ["coloring_a_border.cc"],
    # malloc = "@com_google_tcmalloc//tcmalloc",
    deps = [
        "@com_github_google_glog//:glog",
        "@com_github_gflags_gflags//:gflags",
    ],
    # linkopts = [ '-lunwind', '-lm', '-lpthread', '-lrt', '-ltcmalloc_and_profiler'],
    linkopts = ['-lm', '-lpthread'],
)
cc_binary(
    name = "merge_k_sorted_lists",
    srcs = ["merge_k_sorted_lists.cc"],
    # malloc = "@com_google_tcmalloc//tcmalloc",
    deps = [
        "@com_github_google_glog//:glog",
        "@com_github_gflags_gflags//:gflags",
    ],
    # linkopts = [ '-lunwind', '-lm', '-lpthread', '-lrt', '-ltcmalloc_and_profiler'],
    linkopts = ['-lm', '-lpthread'],
)
cc_binary(
    name = "serialize_and_deserialize_binary_tree",
    srcs = ["serialize_and_deserialize_binary_tree.cc"],
    # malloc = "@com_google_tcmalloc//tcmalloc",
    deps = [
        "@com_github_google_glog//:glog",
        "@com_github_gflags_gflags//:gflags",
    ],
    # linkopts = [ '-lunwind', '-lm', '-lpthread', '-lrt', '-ltcmalloc_and_profiler'],
    linkopts = ['-lm', '-lpthread'],
)
