package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "implement_queue_using_stacks",
    srcs = ["implement_queue_using_stacks.cc"],
    # malloc = "@com_google_tcmalloc//tcmalloc",
    deps = [
        '//third_party/glog:glog',
        '//third_party/gflags:gflags',
    ],
    # linkopts = [ '-lunwind', '-lm', '-lpthread', '-lrt', '-ltcmalloc_and_profiler'],
    linkopts = ['-lm', '-lpthread', '-lrt'],
)

cc_binary(
    name = "daily_temperatures",
    srcs = ["daily_temperatures.cc"],
    # malloc = "@com_google_tcmalloc//tcmalloc",
    deps = [
        '//third_party/glog:glog',
        '//third_party/gflags:gflags',
    ],
    # linkopts = [ '-lunwind', '-lm', '-lpthread', '-lrt', '-ltcmalloc_and_profiler'],
    linkopts = ['-lm', '-lpthread', '-lrt'],
)

cc_binary(
    name = "largest_rectangle_in_histogram",
    srcs = ["largest_rectangle_in_histogram.cc"],
    # malloc = "@com_google_tcmalloc//tcmalloc",
    deps = [
        '//third_party/glog:glog',
        '//third_party/gflags:gflags',
    ],
    # linkopts = [ '-lunwind', '-lm', '-lpthread', '-lrt', '-ltcmalloc_and_profiler'],
    linkopts = ['-lm', '-lpthread', '-lrt'],
)

cc_binary(
    name = "maximal_rectangle",
    srcs = ["maximal_rectangle.cc"],
    # malloc = "@com_google_tcmalloc//tcmalloc",
    deps = [
        '//third_party/glog:glog',
        '//third_party/gflags:gflags',
    ],
    # linkopts = [ '-lunwind', '-lm', '-lpthread', '-lrt', '-ltcmalloc_and_profiler'],
    linkopts = ['-lm', '-lpthread', '-lrt'],
)

cc_binary(
    name = "valid_parentheses",
    srcs = ["valid_parentheses.cc"],
    # malloc = "@com_google_tcmalloc//tcmalloc",
    deps = [
        '//third_party/glog:glog',
        '//third_party/gflags:gflags',
    ],
    # linkopts = [ '-lunwind', '-lm', '-lpthread', '-lrt', '-ltcmalloc_and_profiler'],
    linkopts = ['-lm', '-lpthread', '-lrt'],
)
