package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "satisfiability_of_equality_equations",
    srcs = ["satisfiability_of_equality_equations.cc"],
    # malloc = "@com_google_tcmalloc//tcmalloc",
    deps = [
        '//third_party/glog:glog',
        '//third_party/gflags:gflags',
    ],
    linkopts = ['-lm', '-lpthread', '-lrt'],
    #linkopts = [ '-lunwind', '-lm', '-lpthread', '-lrt', '-ltcmalloc_and_profiler'],
)
